// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiIIAbP0DEgIAPasECdCFlztNudaogG-g',
    appId: '1:528316285377:web:f5539d478624590f36af40',
    messagingSenderId: '528316285377',
    projectId: 'auth-612db',
    authDomain: 'auth-612db.firebaseapp.com',
    storageBucket: 'auth-612db.appspot.com',
    measurementId: 'G-9GT8XLC5YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS6CzPnyTB1tnHzCFCBwLhvtNyvu7m6hc',
    appId: '1:528316285377:android:c847f6688a65069e36af40',
    messagingSenderId: '528316285377',
    projectId: 'auth-612db',
    storageBucket: 'auth-612db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa0fuewYSOLSkIy9Uipze-0Pyth2CT98A',
    appId: '1:528316285377:ios:38198f7f0e55e9ad36af40',
    messagingSenderId: '528316285377',
    projectId: 'auth-612db',
    storageBucket: 'auth-612db.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa0fuewYSOLSkIy9Uipze-0Pyth2CT98A',
    appId: '1:528316285377:ios:38198f7f0e55e9ad36af40',
    messagingSenderId: '528316285377',
    projectId: 'auth-612db',
    storageBucket: 'auth-612db.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiIIAbP0DEgIAPasECdCFlztNudaogG-g',
    appId: '1:528316285377:web:08662e61de55e48d36af40',
    messagingSenderId: '528316285377',
    projectId: 'auth-612db',
    authDomain: 'auth-612db.firebaseapp.com',
    storageBucket: 'auth-612db.appspot.com',
    measurementId: 'G-N5855XJT51',
  );

}